# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metro_interface <- function(num_chains, initial_states, num_steps, seed, n_cores, scale_factor_of_proposal = 1.0) {
    .Call(`_MHParallel_metro_interface`, num_chains, initial_states, num_steps, seed, n_cores, scale_factor_of_proposal)
}

